@startuml


Conference -- BoardMeeting
Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

Person "0..*" -- "0..*" Conference : attends To
BoardMeeting "0..*" -- "0..*" BoardMember : attends To
Event "0..*" -- "0..*" Member : attends To
Location "1"-- "0..*" Event : isLocated In

AAUOC o-- "0..*" Person
AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Location

class AAUOC{
newLocation(l : Location): void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register (m : Member, e : Event) : void
}

class Location{
Description : String
address : String
}

class Event{
date : Date
description :String
assign(l : Location) : void
}

class Person{
name : String
}

class Member{
e-mail : String
}

class Conference{
max_attendees : Integer
}



@enduml