@startuml


Conference -- BoardMeeting
Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

Person -- Conference
BoardMeeting -- BoardMember
Event -- Member
Location -- Event

AAUOC o-- Person
AAUOC o-- Event
AAUOC o-- Location

class AAUOC{
newLocation(l : Location): void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register (m : Member, e : Event) : void
}

class Location{
Description : String
address : String
}

class Event{
date : Date
description :String
assign(l : Location) : void
}

class Person{
name : String
}

class Member{
e-mail : String
}


@enduml