@startuml


Conference -- BoardMeeting
Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

Person -- Conference : attends To
BoardMeeting -- BoardMember : attends To
Event -- Member : attends To
Location -- Event : isLocated In

AAUOC o-- "0..*" Person
AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Location

class AAUOC{
newLocation(l : Location): void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register (m : Member, e : Event) : void
}

class Location{
Description : String
address : String
}

class Event{
date : Date
description :String
assign(l : Location) : void
}

class Person{
name : String
}

class Member{
e-mail : String
}

class Conference{
max_attendees : Integer
}



@enduml